### ISSUE TITLE
`docker run` requires path/port bindings

### ISSUE THREAD

**Issue by totten** [progressivetech/docker-civicrm-buildkit#2]
The README gives these instructions:

```
docker create -v "$(pwd)/civicrm:/var/www/civicrm" -e "DOCKER_UID=$UID" \
  -p 2222:22 -p 8001:8001 --name civicrm-buildkit civicrm-buildkit
docker run civicrm-buildkit
```

However, the path/port bindings do not take effect at runtime, so SSH doesn't work, and `civicrm-buildkit.git` is downloaded multiple times. 

Rather, I need to run:

```
docker create -v "$(pwd)/civicrm:/var/www/civicrm" -e "DOCKER_UID=$UID" \
  -p 2222:22 -p 8001:8001 --name civicrm-buildkit civicrm-buildkit
docker run    -v "$(pwd)/civicrm:/var/www/civicrm" -e "DOCKER_UID=$UID" \
  -p 2222:22 -p 8001:8001 civicrm-buildkit
```

(I have not tested whether the parameters are required for both `create` _and_ `run` or _only_ `run`.)

(Environment: Ubuntu 14.04. Docker version 1.7.0 installed per [docker.com docs](https://docs.docker.com/installation/ubuntulinux/).)

**Comment by jmcclelland** [comment]
Woops. That's a mistake in the documentation. When I wrote `docker run civicrm-buildkit` I meant to write `docker start civicrm-buildkit`. Using create and run is redundant.

I just fixed with 28297f5cb9e967866e1177115426255448c6dfd4.
