### ISSUE TITLE
I was following the readme.md when I found that a repository (my-strech) is missing

### ISSUE THREAD

**Issue by leeand00** [progressivetech/docker-civicrm-buildkit#6]
```
$ docker build -t civicrm-buildkit ./
Sending build context to Docker daemon 123.4 kB
Step 1/29 : FROM my-stretch:latest
repository my-stretch not found: does not exist or no pull access
```
Where is this repository in docker hub?

**Comment by leeand00** [comment]
Nevermind, I changed it to my-jessie and now it's good to go...that's the name of the image we create in the readme.md.

**Comment by jmcclelland** [comment]
Woops! This is a bug - I updated all the code to work with debian stretch - I'm not sure it will work properly on jessie now.

I've just pushed a commit that properly updates all references to my-stretch intead of my-jessie in the readme, etc.

Thanks for the notice.

**Comment by leeand00** [comment]
Let me test it again...with Jessie...
