### ISSUE TITLE
README.md: references to debian stretch instead of bullseye

### ISSUE THREAD

**Issue by JohnXLivingston** [progressivetech/docker-civicrm-buildkit#8]
Hello,

You updated the Dockerfile to use Debian Bullseye, but the README.md has still several references to Debian Stretch.

**Comment by jmcclelland** [comment]
Thanks, should be fixed now.

**Comment by JohnXLivingston** [comment]
found another reference to stretch, and another bug. Fixed in: https://github.com/progressivetech/docker-civicrm-buildkit/pull/9
